name: Web Host
on: workflow_dispatch
jobs:
  hosting-website:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: template
    steps:

      - name: Checking the OS of runner
        run: |
          echo "Runner OS: $RUNNER_OS"

      - name: Checkout code
        uses: actions/checkout@3

      - name: Copy the cods from github to host server
        run: | 
          sudo rm -rf /var/www/html/*
          sudo cp -r * /var/www/html/

      - name: Starting the nginx service
        run: | 
          sudo systemctl restart nginx